### ISSUE TITLE
Is there anyway to set button status manually at the beginning? 

### ISSUE THREAD

**Issue by EgyptianM** [jd-alexander/LikeButton#1]
Hello @jd-alexander 
I wonder if there is any way to set button status as liked or unliked manually before user tabs it
Thank you for your efforts.

**Comment by jd-alexander** [comment]
Ooooh never thought of doing that.  Will have that released later today

**Comment by EgyptianM** [comment]
Thank you 
waiting for it.

**Comment by jd-alexander** [comment]
The feature has been added :) Just update your project 

```gradle
dependencies {
	...
	compile 'com.github.jd-alexander:LikeButton:0.1.3'
	}
}

And check the documentation here : https://github.com/jd-alexander/LikeButton#button-state

**Comment by EgyptianM** [comment]
Thank you very much :+1:
