### ISSUE TITLE
Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.

### ISSUE THREAD

**Issue by radi-ratlh** [jd-alexander/LikeButton#10]
I got the following error while syncing project :
**Error:(3) Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Inverse'.**
I am using appcompat-v7:22.2.1

**Comment by jd-alexander** [comment]
Have you tried using app compat v7 23? That's what I'm using now and build is fine.
