### ISSUE TITLE
Build gradle gets stuck on build when using compile 'com.github.jd-alexander:LikeButton:0.1.6'

### ISSUE THREAD

**Issue by AlexJuca** [jd-alexander/LikeButton#11]
I cant seem to get your library to compile with compile 'com.github.jd-alexander:LikeButton:0.1.6'
I added maven { url "https://jitpack.io" } to my build gradle file. Gradle does not display any error.

Would appreciate some help with  this.

**Comment by jd-alexander** [comment]
I made a fix that was causing the build to fail so try with version 0.1.7 and make sure that your compile sdk in your build.gradle is at least API 23
