### ISSUE TITLE
Error:Failed to resolve: com.android.support:appcompat-v7:23.1.1

### ISSUE THREAD

**Issue by TellH** [jd-alexander/LikeButton#13]
how can i fix it

**Comment by jd-alexander** [comment]
Ensure that you are compiling against sdk 23

**Comment by TellH** [comment]
compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "com.example.tlh.autohidebottombar"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
I check my build.gradle file, my compileSdkVersion is exactly 23. What should I do next?
