### ISSUE TITLE
Even when changing iconsize the buttons are all tiny

### ISSUE THREAD

**Issue by kiaanpillay** [jd-alexander/LikeButton#14]
I dont know if I'm the only person with this problem but all the buttons are tiny and no matter what I can't change them. I even tried using your example xml with no luck. It looks perfect otherwise, beautiful work. I attached a photo using your example XML
![screenshot_2016-02-14-00-41-35](https://cloud.githubusercontent.com/assets/7480712/13030440/0771326e-d2b4-11e5-9ca7-3cd0493ed442.png)

**Comment by jd-alexander** [comment]
let me see the XML that you are using to create these buttons.

**Comment by jd-alexander** [comment]
Did you run the example? Aren't the sizes large in it??

**Comment by kiaanpillay** [comment]
`<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools" android:layout_width="match_parent"
    android:layout_height="match_parent" android:paddingLeft="@dimen/activity_horizontal_margin"
    android:paddingRight="@dimen/activity_horizontal_margin"
    android:paddingTop="@dimen/activity_vertical_margin"
    android:paddingBottom="@dimen/activity_vertical_margin"
    tools:context="hakobob.pelichat.Activities.BoardActivity">
    <?xml version="1.0" encoding="utf-8"?>



    <LinearLayout
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_centerHorizontal="true"
        android:orientation="horizontal">

        <com.like.LikeButton
            tools:liked="true"
            android:id="@+id/star_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            tools:icon_size="25dp"
            tools:icon_type="star" />

        <com.like.LikeButton
            android:id="@+id/heart_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            tools:icon_size="25dp"
            tools:anim_scale_factor="3"
            tools:icon_type="heart" />

        <com.like.LikeButton
            android:id="@+id/thumb_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            tools:circle_end_color="@android:color/holo_blue_dark"
            tools:circle_start_color="@android:color/holo_blue_bright"
            tools:dots_primary_color="@android:color/holo_blue_light"
            tools:dots_secondary_color="@android:color/holo_blue_dark"
            tools:icon_size="25dp"
            tools:like_drawable="@drawable/thumb_on"
            tools:unlike_drawable="@drawable/thumb_off" />

        <com.like.LikeButton
            android:id="@+id/smile_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            tools:circle_end_color="@android:color/holo_purple"
            tools:circle_start_color="@android:color/holo_purple"
            tools:dots_primary_color="@android:color/holo_blue_dark"
            tools:dots_secondary_color="@android:color/holo_blue_light"
            tools:icon_size="25dp" />
    </LinearLayout>


</RelativeLayout>
`

**Comment by kiaanpillay** [comment]
Thanks for the quick reply

**Comment by kiaanpillay** [comment]
I did not run the example, my Android Studio was acting up so I just ran it in my project

**Comment by kiaanpillay** [comment]
I am specifically trying to use it is a CardView

**Comment by jd-alexander** [comment]
Sorry I have been missing. Did you get this to work?

**Comment by waniolka** [comment]
Same error here...

**Comment by jd-alexander** [comment]
What are you experiencing? Which view is it in? DId you run the example?

**Comment by Ascendance** [comment]
exactly the same problem

**Comment by jd-alexander** [comment]
@Ascendance does the example work? what kind of layout are you having this issue in. need a sample project reproducing the issue so I can debug.

**Comment by zboing** [comment]
this issue happens because you are using:
xmlns:app="http://schemas.android.com/tools" 
instead of 
xmlns:app="http://schemas.android.com/apk/res-auto"
