### ISSUE TITLE
Icon stays small when click then swipe off

### ISSUE THREAD

**Issue by csbenz** [jd-alexander/LikeButton#15]
If I click on the button, stay down, move my finger off the button then lift my finger off the screen, the LikeButton stays small.

**Comment by jd-alexander** [comment]
I dont understand.Give me more information so I can try to reproduce this issue.

**Comment by csbenz** [comment]
I tried reproducing the issue in a new fragment but everything works now. Seems to be a bug with the specific way I'm using the library.

**Comment by csbenz** [comment]
The issue occurs when the LikeButton is part of a ViewPager. It's like if it doesn't catch an "onLiftFingerFromScreen" touch event or something. Any idea?

**Comment by csbenz** [comment]
See [this line](https://github.com/jd-alexander/LikeButton/blob/master/likebutton/src/main/java/com/like/LikeButton.java#L254)

**Comment by jd-alexander** [comment]
Okay im not sure how to address it. Gonna check into it some more this weekend though.

**Comment by andyxialm** [comment]
I met the same issue. When I pressed the button (action_down), then move my finger to stay away from this view.  Leave the screen. At this time, the likebutton won't be restoring size.

**Comment by barykaed** [comment]
I'm seeing this issue when using the button in a recyclerview.

**Comment by jd-alexander** [comment]
This solution should solve the issue. Just simply pass the touch event from the viewpager to the button itself.
http://stackoverflow.com/questions/10243690/onclick-on-viewpager-not-triggered
 I will try my best to update it soon with a fix.

**Comment by csbenz** [comment]
I tried fixing the problem using your link but without success.

**Comment by jd-alexander** [comment]
I just placed the button inside a scrollview thats inside a viewpager and i am not able to recreate the issue.

**Comment by AnswerZhao** [comment]
I have encount the same issues. In the Recyclerview, when i swipe the list after clicking the LikeButton, the likebutton  become small.

**Comment by AnswerZhao** [comment]
@andyxialm how can you resolve it, thx ?请问你最后怎么解决的，谢谢。

**Comment by andyxialm** [comment]
@AnswerZhao 暂时弃用了这个方案。等作者fix吧

**Comment by 0wiky0** [comment]
@csbenz  And  @All 
First, I hope you have solved this problem! :-）
There is a rough method to deal whit it: 
     this issue occurs because of sliding conflict, so i think if you use the LikeButton in slidable view ,you'd better move the animate operation in ACTION_DOWN into ACTION_UP . Just like the code:
```
 switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
//                icon.animate().scaleX(0.7f).scaleY(0.7f).setDuration(150).setInterpolator(DECCELERATE_INTERPOLATOR);
                setPressed(true);
                break;

            case MotionEvent.ACTION_MOVE:
                float x = event.getX();
                float y = event.getY();
                boolean isInside = (x > 0 && x < getWidth() && y > 0 && y < getHeight());
                if (isPressed() != isInside) {
                    setPressed(isInside);
                }
                break;

            case MotionEvent.ACTION_UP:
                icon.animate().scaleX(0.7f).scaleY(0.7f).setDuration(150).setInterpolator(DECCELERATE_INTERPOLATOR);
                icon.animate().scaleX(1).scaleY(1).setInterpolator(DECCELERATE_INTERPOLATOR);
                if (isPressed()) {
                    performClick();
                    setPressed(false);
                }
                break;
        }

```
I hope it work for you!

**Comment by AnswerZhao** [comment]
@0wiky0 Yes, it's a simple and rough way, and i have the same idea.

**Comment by jd-alexander** [comment]
Okay I am going to apply this fix and release a new version soon. How can I go about reproducing this problem so I can be sure that it's fixed?

**Comment by jd-alexander** [comment]
Applied the fix and released a new version. Thanks for your help @0wiky0  and others.

**Comment by csbenz** [comment]
@jd-alexander works great thanks! :)
