### ISSUE TITLE
Can't compile gradle

### ISSUE THREAD

**Issue by ivandiazmolina** [jd-alexander/LikeButton#18]
I have the next error when I try to compile your gradle

Error:(42, 13) Failed to resolve: com.github.jd-alexander:LikeButton:0.1.9.

 I had 0.1.8 and worked, but now did not work any version.

I create a new project , copy/paste gradle and fail too.

My config
--------------
classpath 'com.android.tools.build:gradle:1.5.0'
compileSdkVersion 23
buildToolsVersion "23.0.2"
minSdkVersion 15
targetSdkVersion 23

**Comment by jd-alexander** [comment]
Ok I will roll it back then until I can find a fix. Use the older version. 0.1.8

**Comment by ivandiazmolina** [comment]
Yes but now not compile any version, I dont know the reason but only happend with your gradle :(

**Comment by jd-alexander** [comment]
You tried 0.1.8

**Comment by dfloresgonz** [comment]
does not work
