### ISSUE TITLE
enabled attribute for the button throws an error when used with Preference support library

### ISSUE THREAD

**Issue by raylee4204** [jd-alexander/LikeButton#22]
Because Preference support library already defines "enabled" attribute, using LikeButton library won't compile.

**Comment by jd-alexander** [comment]
did you use the prefix before the attribute?

**Comment by raylee4204** [comment]
Yeah I did. The support lib uses the "enabled" value already. I suggest you should use something other than that

**Comment by jd-alexander** [comment]
Okay I am going to make that change now and push an update. Sorry for the
issue.

**Comment by jd-alexander** [comment]
Release a new version of the library 0.2.0 that should resolve this issue.
