### ISSUE TITLE
Add text view

### ISSUE THREAD

**Issue by sandeshlasnapure** [jd-alexander/LikeButton#24]
Is there any way to add text view? and also touch area is very small I have to touch on icon only.
I need button like layout. So if click on text or icon it should react on action.
Like facebook button.
And I have tried with padding but no luck.
Thanks.

**Comment by jd-alexander** [comment]
You wrap but button and the textview in one layout and then use the margin to position the textview closer to the button. The button has an invisible area around that's used for the animation that's the reason why there's a big gap when it's placed next to something else.
