### ISSUE TITLE
With 

### ISSUE THREAD

**Issue by edsphinx** [jd-alexander/LikeButton#27]
Just added the dependency and don't let me even compile with the next errors:

/Users/edsphinx/Documents/DEMO Project/DEMO/app/build/intermediates/exploded-aar/com.afollestad.material-dialogs/core/0.8.5.0/res/values-v11/values-v11.xml

No resource found that matches the given name (at 'android:actionModeCloseDrawable' with value '@drawable/abc_ic_ab_back_mtrl_am_alpha')

Error:Execution failed for task ':app:processDebugResources'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Users/edsphinx/Library/Android/sdk/build-tools/23.0.2/aapt'' finished with non-zero exit value 1

Using:
compileSdkVersion 23
buildToolsVersion '23.0.2'

**Comment by jd-alexander** [comment]
That error is not related to this library. Its coming from the Material
Dialogs library.

Joel Dean,
Software Engineer
