### ISSUE TITLE
How to find the state of the button if it is liked or not?

### ISSUE THREAD

**Issue by kartikkumar1994** [jd-alexander/LikeButton#28]

**Comment by jd-alexander** [comment]
Explain this in more detail. You can get the state by using the listener when the click is made.

**Comment by jenlai1345** [comment]
Supposed I have 2 Like buttons.
If button 1 is liked, I'd like to check button 2's state (and if it's on/liked, I'd like to switch it off).
Is there a way to get the current state?
for example, button.liked ?
