### ISSUE TITLE
The library reverses layout direction

### ISSUE THREAD

**Issue by EgyptianM** [jd-alexander/LikeButton#3]
Hello friend @jd-alexander   
I just added your awesome library to an English localized project and I'm using Arabic as my language on my phone
when I run my app on my phone all views are reversed to be RTL 
when I use English as my language on the phone everything is OK
but what if the user is using a RTL language on his phone like me?
This wasn't happening before adding likebutton library
What is the possible cause for that?

**Comment by jd-alexander** [comment]
I am not sure . I would have to do some research and get back to you with that.

**Comment by EgyptianM** [comment]
Thank you very much my friend :)

**Comment by jd-alexander** [comment]
So isn't the views supposed to be reversed when RTL support is enabled? What exactly is the error you are experiencing? I don't quite understand.

**Comment by EgyptianM** [comment]
Yeah this supposed to happen when the app have a localization for RTL language like when I have an Arabic translation in my app and this will be awesome but this is not good when you have English only in your app and this isn't supposed to happen

Here is some screen shots
this is before adding the library

![screenshot_2016-01-01-08-53-23](https://cloud.githubusercontent.com/assets/12565380/12070084/c2381790-b066-11e5-867a-edf14e7974e7.jpeg)

![screenshot_2016-01-01-09-02-18](https://cloud.githubusercontent.com/assets/12565380/12070085/cbcb7266-b066-11e5-8386-04edc792ed40.jpeg)


and this is after 

notice the tabstrip went out of the view

![screenshot_2016-01-01-08-58-22](https://cloud.githubusercontent.com/assets/12565380/12070086/f1e633f0-b066-11e5-80e5-d8b2817a3c9e.jpeg)

![screenshot_2016-01-01-08-59-26](https://cloud.githubusercontent.com/assets/12565380/12070088/fefa8910-b066-11e5-9848-0d60b510ab77.jpeg)

**Comment by jd-alexander** [comment]
Try this solution : http://stackoverflow.com/questions/22963740/rtl-support-disabling-it-only-for-specific-ui-components 
So let the layoutDirection in the Like Button XML to android:layoutDirection="ltr"
            <com.like.LikeButton
            app:icon_type="heart"
            android:layoutDirection="ltr"
            app:icon_size="25dp"
            android:id="@+id/star_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"/>

**Comment by EgyptianM** [comment]
The problem is not happening when I use buttons. It happens when I put the library in the dependencies immediately and before I use it at all.  
The issue is not in like buttons elements, the whole layout is getting inverse  when I put the library in the app dependencies.

**Comment by EgyptianM** [comment]
You can import it into any sample app and change your phones language to Arabic or any other rtl language and see what will happen and try it without using like buttons.

**Comment by jd-alexander** [comment]
Ok that's weird. Im going to check it out soon.

**Comment by EgyptianM** [comment]
Thank you 
I'm waiting for it
And one more question
Where from do you get the smile buttons drawable?
I can't find it.

**Comment by EgyptianM** [comment]
Solved!
Just removed `android:supportsRtl="true"` from library manifest .
Thank you.

**Comment by jd-alexander** [comment]
Okay glad to know it worked out :+1:
