### ISSUE TITLE
Allow long clicks

### ISSUE THREAD

**Issue by AdityaAnand1** [jd-alexander/LikeButton#32]
Currently, `setOnLongClickListener` doesn't work with LikeButton. I attempted to make some tweaks, 

* Setting `this.setOnLongClickListener(this);` in the LikeButton class's init(..), with a placeholder implementation of LongClickListener. I first thought that this should work as I registered the listener in the view class, but for some reason it doesn't.
* I tried overriding onTouchListener and manually extracting long clicks, but unsurprisingly this interferes with LikeButton's onTouch.

In the context of LikeButton, the long click shouldn't actually do anything (like toggling the like button), but simply allow us to add our own behavior. In my case, I like adding little tooltip pop-ups to my icon buttons so that people know what they do. Like when you long press a toolbar's menu icons. I'd like to do this with LikeButton.

This could be a simple addition that doesn't interrupt any other functions of LikeButton.

**Comment by jd-alexander** [comment]
Okay thanks for the info. If you could submit this modification as a pull request I would greatly appreciate it.
