### ISSUE TITLE
Alterations in XML don't work

### ISSUE THREAD

**Issue by siloebb** [jd-alexander/LikeButton#34]
I'm trying change the size and chance the icon of the LikeButton, but in the XML don't work, if I use programmatically work well.

It's a simple change.
I use Moto G 1 with Android 5.1

> <com.like.LikeButton
>             app:icon_type="heart"
>             app:icon_size="60dp"
>             app:like_drawable="@drawable/ic_favorite_black_24dp"
>             app:unlike_drawable="@drawable/ic_favorite_border_black_24dp"
>             android:id="@+id/feed_curtir"
>             android:layout_width="wrap_content"
>             android:layout_height="wrap_content"
>             />

**Comment by jd-alexander** [comment]
Okay I am going to check this out.

**Comment by kavyaub** [comment]
I'm facing the same problem. Unable to set the icon size in XML.

**Comment by jd-alexander** [comment]
Okay gonna take a look at it later today.

**Comment by kavyaub** [comment]
@jd-alexander Actually, it's working on XML, it's just not showing up in the preview.

**Comment by jd-alexander** [comment]
alright thanks for pointing that out. Was literally just opening up the project.

**Comment by tamtom** [comment]
oh yeah lets just close this issue without fixing it
