### ISSUE TITLE
Animations not working in recycler view adapter

### ISSUE THREAD

**Issue by asifali22** [jd-alexander/LikeButton#35]
I'm trying to animate it with 
          `holder.plus_like.setCircleEndColorRes(R.color.colorAccent);
           holder.plus_like.setCircleStartColorRes(R.color.colorPrimary);
            holder.plus_like.setExplodingDotColorsRes(R.color.colorAccent, R.color.colorPrimary);
            holder.plus_like.setAnimationScaleFactor(1);`
But no animation happens when i click on the button.

**Comment by asywalulfikri** [comment]
yes right. when i set In adapter. animation not work. when give holder.plusLike.setOnClickListener(new View.OnClickListener()

**Comment by asifali22** [comment]
@asywalulfikri  I'm not sure but try adding `holder.plusLike.setOnLikeListener(...);` i.e. the **custom like listener** method provided by @jd-alexander  . I haven't _tested_ it with that as of now, but please do try it and let me know if it works. Thanks for the feedback though.

**Comment by asywalulfikri** [comment]
oke @asifali22

**Comment by jd-alexander** [comment]
Did you ever get this to work?

**Comment by ramifarag** [comment]
it worked with me like the below:

public static class ViewHolder extends RecyclerView.ViewHolder {
        public LikeButton starButton;
        ....
            starButton = (LikeButton) itemView.findViewById(R.id.star_button);

    @Override
    public void onBindViewHolder(final HomeHolder viewHolder, final int position) {
        viewHolder.starButton.setTag(position);
        ...
        viewHolder.starButton.setLikeDrawable(new BitmapDrawable(activity.getResources(), new IconicsDrawable(activity, CommunityMaterial.Icon.cmd_star).colorRes(android.R.color.holo_purple).sizeDp(25).toBitmap()));
        viewHolder.starButton.setUnlikeDrawable(new BitmapDrawable(activity.getResources(), new IconicsDrawable(activity, CommunityMaterial.Icon.cmd_star).colorRes(android.R.color.darker_gray).sizeDp(25).toBitmap()));
viewHolder.starButton.setOnLikeListener(new OnLikeListener() {
            @Override
            public void liked(LikeButton likeButton) {
// do what ever you want
}
@Override
            public void unLiked(LikeButton likeButton) {
// do what ever you want
}

**Comment by jd-alexander** [comment]
This issue seems to have been resolved. Closing.
