### ISSUE TITLE
weird behavior in Expandable List View  

### ISSUE THREAD

**Issue by ghost** [jd-alexander/LikeButton#36]
i used your library in a Expandable List View as the child's fav button but after clicking on one button randomly other buttons will change !
for example i choose 
group 1 > child 1
after that 
Group 20 > child 2 + child 4 
Group 13 > child 1 
group 25 > child 2 + child 4 
are selected too !

**Comment by luizfp** [comment]
If you recycle your views using a ViewHolder but you don't have any logic to control each item you have to show selected or not this is the expected behavior and not a bug.
