### ISSUE TITLE
Icon type not changing

### ISSUE THREAD

**Issue by DamanSingh4321** [jd-alexander/LikeButton#37]
app:icon_type="star"
It shows heart icon only. Icon type not working.

**Comment by dsh0416** [comment]
I've met similar problem with you. I fix it through manually set the `xmlns:app`, because the link automatically generated by Android Studio is incorrect. Use ` xmlns:app="http://schemas.android.com/apk/res-auto"` in xml, and it works.

**Comment by KarmatechMediaworks** [comment]
DO by the java code:
setIcon(IconType.Thumb)
