### ISSUE TITLE
Animation of Like Button(Expanding Dots) must be on top level layout (no need to wrap it)  

### ISSUE THREAD

**Issue by singhania1408** [jd-alexander/LikeButton#41]

**Comment by jd-alexander** [comment]
Explain this some more so I investigate if this can be writtten in a better way.

**Comment by b2cbd** [comment]
Currently need a fixed layout size to execute animation... If layout is smaller than expected size, animated ball will be clipped(hidden).

@singhania1408 Found a solution for this. Add android:clipChildren="false" and android:clipToPadding="false" to all layouts and bring view front  likeButtonView.bringToFront()

@jd-alexander if you find more convenient way inside the library, that will be helpful.
