### ISSUE TITLE
Cannot add in gradle 0.2.0

### ISSUE THREAD

**Issue by 60noy** [jd-alexander/LikeButton#42]
Error:Could not find com.github.jd-alexander:LikeButton:0.2.0.
Required by:
    [myAppName]:app:unspecified
Search in build.gradle files

What can I do? I tried older versions and still cannot compile them. The problem is only with this package. I compiled a lot of other packages successfully.

**Comment by akashjpro** [comment]
You can download source and then copy class make library. You can use it. hihi
