### ISSUE TITLE
Weird animation behaviour in RecyclerView

### ISSUE THREAD

**Issue by aresaguilar** [jd-alexander/LikeButton#45]
When using the star in a RecyclerView, the animation appears on the item before rather than the one clicked.

**Comment by jd-alexander** [comment]
Could you give me some more details about this?

**Comment by aresaguilar** [comment]
@jd-alexander Sure! I'm using it on this project (on that commit, I finally removed it because of the bug): https://github.com/aresaguilar/PopularMovies/tree/a3c73fe943b44596496b469ff7ce19fb92177c2d

I'm using it in the file popularmovies/view/adapter/MovieAdapter.java, registering it's listener on the ViewHolder class:
```java
public MovieViewHolder(View itemView) {
            super(itemView);

            /* ... */

            listItemFavoriteButton = (LikeButton) itemView.findViewById(R.id.btn_item_star);
            listItemFavoriteButton.setOnLikeListener(
                    new OnLikeListener() {
                        @Override
                        public void liked(LikeButton likeButton) {
                            String movieId = (String) likeButton.getTag();
                            mListener.onListItemStar(movieId);
                        }

                        @Override
                        public void unLiked(LikeButton likeButton) {
                            String movieId = (String) likeButton.getTag();
                            mListener.onListItemUnstar(movieId);
                        }
                    });
        }
```

And binding it with this function:
```java
    void bind(int position) {
            /* Move cursor to my position */
            if (!mCursor.moveToPosition(position)) {
                Log.e(TAG, "Error moving cursor to position " + position);
                return;
            }

            /* ... */

            listItemFavoriteButton.setTag(movieId);

            Cursor cursor = mContext.getContentResolver().query(
                    MoviesContract.FavoriteMoviesEntry.CONTENT_URI.buildUpon().appendPath(movieId).build(),
                    null, null, null, null);

            if (cursor.getCount() > 0) {
                listItemFavoriteButton.setLiked(true);
            } else {
                listItemFavoriteButton.setLiked(false);
            }

            /* ... */

        }
```

The bug is that when clicking one star, it marks as clicked and correctly inserts the item in the database. However, the animation (the explosion of the star) happens on the item before (IOW, the listener is called with the correct ID, but the animation happens in the RecyclerView item in the previous position).

**Comment by PigFlyy** [comment]
@jd-alexander I think u'd better after animation end or cancel  call the OnLikeListener,or give more interface options in the OnLikeListener

**Comment by jd-alexander** [comment]
Okay I understand I am going to look into making this modification. Thanks for your input.

**Comment by jd-alexander** [comment]
The animation end listener functionality has been added. Will work on depreciating on like or just merging the functionality soon. #60

**Comment by grezzled** [comment]
I'm facing the same problem, what can I do with onAnimationEnd to solve this problem! this issue should not be closed yet!
