### ISSUE TITLE
Can i disable animation on heart button

### ISSUE THREAD

**Issue by dhavalkba** [jd-alexander/LikeButton#47]
I want to disable animation of heart button,when i click on heart button first time animation is appear that animation i want to disable(just change selected & unselected change icon).

**Comment by jd-alexander** [comment]
I dont understand. This is an animation library. Why would you want to disable it?

**Comment by dhavalkba** [comment]
i know this is animation library but i want just change images on first & second time click on button,
in this library you add option for disable animation so i can use this library.

**Comment by jd-alexander** [comment]
I am sorry but that's outside the scope of the library at the moment. If you want this functionality you can alwas fork the library and add it.

**Comment by dhavalkba** [comment]
I Think you should be add disable animation.
