### ISSUE TITLE
Need to remove animation for like button when liked.

### ISSUE THREAD

**Issue by MichaelReyes** [jd-alexander/LikeButton#48]
Hi, 
Can you help me? I need to remove animation when likeButton is liked. It just need to be plain that when likeButton is liked it will just be a red heart without animations.

Thanks.

**Comment by jd-alexander** [comment]
Greetings, I will try to add this functionality shortly. Might have it ready by no sooner than this weekend.

**Comment by MichaelReyes** [comment]
Ok sir. Thanks.

**Comment by jd-alexander** [comment]
This functionality is already available. All you have to do is set the like button's enabled method to false in the OnLikeListener
