### ISSUE TITLE
VectorDrawable isssue on 0.2.1

### ISSUE THREAD

**Issue by nAkhmedov** [jd-alexander/LikeButton#49]
05-14 00:20:14.687 27791-27791/com.nakhmedov.finance W/System.err: android.view.InflateException: Binary XML file line #2: Error inflating class com.like.LikeButton
05-14 00:20:14.697 27791-27791/com.nakhmedov.finance W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:620)
05-14 00:20:14.697 27791-27791/com.nakhmedov.finance W/System.err:     at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:696)
05-14 00:20:14.697 27791-27791/com.nakhmedov.finance W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:469)
05-14 00:20:14.697 27791-27791/com.nakhmedov.finance W/System.err:     at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.view.menu.MenuItemImpl.setActionView(MenuItemImpl.java:624)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.view.menu.MenuItemImpl.setActionView(MenuItemImpl.java:43)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v4.view.MenuItemCompat.setActionView(MenuItemCompat.java:310)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:469)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:483)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:200)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.view.SupportMenuInflater.inflate(SupportMenuInflater.java:122)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at com.nakhmedov.finance.ui.fragment.SelectedCategory.onCreateOptionsMenu(SelectedCategory.java:136)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v4.app.Fragment.performCreateOptionsMenu(Fragment.java:2291)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v4.app.FragmentManagerImpl.dispatchCreateOptionsMenu(FragmentManager.java:3011)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v4.app.FragmentController.dispatchCreateOptionsMenu(FragmentController.java:328)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v4.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:363)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.app.AppCompatDelegateImplBase$AppCompatWindowCallbackBase.onCreatePanelMenu(AppCompatDelegateImplBase.java:335)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:98)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:454)
05-14 00:20:14.707 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v7.app.ToolbarActionBar$1.run(ToolbarActionBar.java:61)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at android.os.Handler.handleCallback(Handler.java:730)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:92)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at android.os.Looper.loop(Looper.java:213)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5225)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at java.lang.reflect.Method.invokeNative(Native Method)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at java.lang.reflect.Method.invoke(Method.java:525)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:741)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:557)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at dalvik.system.NativeStart.main(Native Method)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err: Caused by: java.lang.reflect.InvocationTargetException
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at java.lang.reflect.Constructor.constructNative(Native Method)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err:     at android.view.LayoutInflater.createView(LayoutInflater.java:594)
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err: 	... 29 more
05-14 00:20:14.717 27791-27791/com.nakhmedov.finance W/System.err: Caused by: android.content.res.Resources$NotFoundException: File res/drawable/ic_heart_like_white_vector.xml from drawable resource ID #0x7f020082
05-14 00:20:14.737 27791-27791/com.nakhmedov.finance W/System.err:     at android.content.res.Resources.loadDrawable(Resources.java:2103)
05-14 00:20:14.737 27791-27791/com.nakhmedov.finance W/System.err:     at android.content.res.Resources.getDrawable(Resources.java:702)
05-14 00:20:14.737 27791-27791/com.nakhmedov.finance W/System.err:     at android.support.v4.content.ContextCompat.getDrawable(ContextCompat.java:374)
05-14 00:20:14.737 27791-27791/com.nakhmedov.finance W/System.err:     at com.like.LikeButton.getDrawableFromResource(LikeButton.java:144)
05-14 00:20:14.737 27791-27791/com.nakhmedov.finance W/System.err:     at com.like.LikeButton.init(LikeButton.java:92)
05-14 00:20:14.737 27791-27791/com.nakhmedov.finance W/System.err:     at com.like.LikeButton.<init>(LikeButton.java:67)
05-14 00:20:14.737 27791-27791/com.nakhmedov.finance W/System.err:     at com.like.LikeButton.<init>(LikeButton.java:62)
05-14 00:20:14.737 27791-27791/com.nakhmedov.finance W/System.err: 	... 32 more

**Comment by nAkhmedov** [comment]
It is not working pre Lollipop versions, Thanks in advance.

**Comment by jd-alexander** [comment]
Do you have this in your application class? 

public class App extends Application {

static {
    AppCompatDelegate.setCompatVectorFromResourcesEnabled(true);
}

**Comment by nAkhmedov** [comment]
Yes it helped, thank you

**Comment by jd-alexander** [comment]
Awesome, Happy to help.
