### ISSUE TITLE
How to know which button was tapped when implementing OnLikeListener?

### ISSUE THREAD

**Issue by EgyptianM** [jd-alexander/LikeButton#5]
Hello @jd-alexander 
I wonder how would I know which button was tapped in methods liked() and unlided() when I implement `OnLikeListener`

as I see those methods take no views or any other params to identify which button was tapped.

**Comment by jd-alexander** [comment]
Oh okay will update and pass the view.

**Comment by EgyptianM** [comment]
Thank you my friend :)

**Comment by jd-alexander** [comment]
Yes update coming soon.

**Comment by jd-alexander** [comment]
I paused the LikeButton to the event listener. See docs for details : https://github.com/jd-alexander/LikeButton#like-event-listener

**Comment by EgyptianM** [comment]
Thank you very much :+1:
