### ISSUE TITLE
doesn't work on 4.4.2

### ISSUE THREAD

**Issue by sigma1994** [jd-alexander/LikeButton#51]
it doesn't work on android below 5.0 !

**Comment by alexprazeres** [comment]
I'm testing it right now on android emulator with API 16 - 4.1.2... It's fine for me,  i'll do further tests.

**Comment by sigma1994** [comment]
i think problem is using vectors with it on API <21

**Comment by jd-alexander** [comment]
What exactly doesnt work? Saying it doesnt work is so vague.

**Comment by sigma1994** [comment]
when i use this code, it make the app crash in API<21 
<com.like.LikeButton
                                android:id="@+id/likeButton"
                                android:layout_width="40dp"
                                android:layout_height="40dp"
                                android:layout_gravity="end|bottom"
                                android:layout_margin="8dp"
                                android:layout_marginStart="8dp"
                                android:layout_marginTop="8dp"
                                app:anim_scale_factor="2"
                                app:circle_end_color="@android:color/holo_red_light"
                                app:circle_start_color="@color/colorPrimary"
                                app:dots_primary_color="@color/colorPrimary"
                                app:dots_secondary_color="@android:color/holo_red_light"
                                app:icon_size="34dp"
                                app:icon_type="Heart"
                                app:is_enabled="true"
                                app:like_drawable="@drawable/heart_fill"
                                app:liked="false"
                                app:unlike_drawable="@drawable/heart_empty" />

drawables are vectors and i have enabled app compact support library with this code in gradle

//drawable support
vectorDrawables.useSupportLibrary = true


with all of this, the app will crash !

**Comment by sigma1994** [comment]
here's the complete codes

`<com.like.LikeButton
                                android:id="@+id/likeButton"
                                android:layout_width="40dp"
                                android:layout_height="40dp"
                                android:layout_gravity="end|bottom"
                                android:layout_margin="8dp"
                                android:layout_marginStart="8dp"
                                android:layout_marginTop="8dp"
                                app:anim_scale_factor="2"
                                app:circle_end_color="@android:color/holo_red_light"
                                app:circle_start_color="@color/colorPrimary"
                                app:dots_primary_color="@color/colorPrimary"
                                app:dots_secondary_color="@android:color/holo_red_light"
                                app:icon_size="34dp"
                                app:icon_type="Heart"
                                app:is_enabled="true"
                                app:like_drawable="@drawable/heart_fill"
                                app:liked="false"
                                app:unlike_drawable="@drawable/heart_empty" /`





//heart_fill

`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportHeight="24"
    android:viewportWidth="24">
    <path
        android:fillColor="@android:color/holo_red_light"
        android:pathData="M12,21.35L10.55,20.03C5.4,15.36 2,12.27 2,8.5C2,5.41 4.42,3 7.5,3C9.24,3 10.91,3.81 12,5.08C13.09,3.81 14.76,3 16.5,3C19.58,3 22,5.41 22,8.5C22,12.27 18.6,15.36 13.45,20.03L12,21.35Z" />
</vector>` 


//heart_empty

`<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportHeight="24"
    android:viewportWidth="24">
    <path
        android:fillColor="@android:color/holo_red_light"
        android:pathData="M12.1,18.55L12,18.65L11.89,18.55C7.14,14.24 4,11.39 4,8.5C4,6.5 5.5,5 7.5,5C9.04,5 10.54,6 11.07,7.36H12.93C13.46,6 14.96,5 16.5,5C18.5,5 20,6.5 20,8.5C20,11.39 16.86,14.24 12.1,18.55M16.5,3C14.76,3 13.09,3.81 12,5.08C10.91,3.81 9.24,3 7.5,3C4.42,3 2,5.41 2,8.5C2,12.27 5.4,15.36 10.55,20.03L12,21.35L13.45,20.03C18.6,15.36 22,12.27 22,8.5C22,5.41 19.58,3 16.5,3Z" />
</vector>`

**Comment by jd-alexander** [comment]
I am going to investigate this issue and get back to you.

**Comment by sigma1994** [comment]
i found why it's not working, issue solved when using this support libraries version 25.3.1, problem was caused by using version 26.0.* !

**Comment by jd-alexander** [comment]
Okay glad you figured it out :)
