### ISSUE TITLE
How to keep like/dislike button state?

### ISSUE THREAD

**Issue by Zukune** [jd-alexander/LikeButton#53]
Hi there! The button works smoothly but by the time I restart the app the buttons comes back to the default state.. So how can I keep the like/dislike state? Thank you
My settings
<com.like.LikeButton

            android:id="@+id/star_button"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:icon_size="20dp"
            app:icon_type="heart"
            app:liked="false"
            app:is_enabled="true"/>

**Comment by jd-alexander** [comment]
At the moment the button doesn't support this. However you could always just save the state when the activity is being destroyed and restore the state and set the state of LikeButton.
