### ISSUE TITLE
Weird behaviour with  RecyclerView ....

### ISSUE THREAD

**Issue by mohamedebrahim96** [jd-alexander/LikeButton#56]
Weird behaviour with  RecyclerView ....the like button keeps appers enabled

**Comment by mohamedebrahim96** [comment]
`public class PostsAdapter extends RecyclerView.Adapter<PostsAdapter.PostsViewHolder>  {

    public List<Data> qoutes;
    public Context context;
    public View view;
    public PostsAdapter(List<Data> qoutes, Context context) {
        this.qoutes = qoutes;
        this.context = context;
    }

    @Override
    public PostsAdapter.PostsViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {



        if (viewType == 1)
            view = LayoutInflater.from(parent.getContext()).inflate(R.layout.first_item, parent, false);
        else {
            view = LayoutInflater.from(parent.getContext()).inflate(R.layout.cardview, parent, false);
        }


        return new PostsViewHolder(view);
    }


    @Override
    public void onBindViewHolder(final PostsViewHolder holder, final int position) {


        if (position != 0) {
            Typeface face = Typeface.createFromAsset(context.getAssets(),
                    "fonts/reqaa-Regular.ttf");
            holder.qoute.setTypeface(face);
            String x = qoutes.get(position).getText();
            String my_new_str = x.replaceAll("[A-Za-z0-9!@#$.//__:%^&*]", "");

            if (qoutes.get(position).extendedEntities != null) {
                Glide.with(context)
                        .load(qoutes.get(position).getExtendedEntities().getMedia().get(0).getMediaUrl())
                        .into(holder.thumbnail);
            }
            if (qoutes.get(position).retweetedStatus != null) {


                holder.favourit_count.setText(qoutes.get(position).getRetweetedStatus().getFavorite_count());

            } else {
                holder.favourit_count.setText(qoutes.get(position).getFavoriteCount());
            }
            holder.qoute.setText(my_new_str);
            holder.seen_count.setText(qoutes.get(position).getRetweetCount());
        }



        holder.like_button.setOnLikeListener(new OnLikeListener(){
            @Override
            public void liked(LikeButton likeButton) {
                Toast.makeText(context, "Liked!", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void unLiked(LikeButton likeButton) {
                Toast.makeText(context, "Liked!", Toast.LENGTH_SHORT).show();
            }
        });


    }

    @Override
    public int getItemCount() {

        return qoutes.size();
    }

    @Override
    public int getItemViewType(int position) {

        if (position == 0) {
            return 1;
        } else {
            return 2;
        }

    }













    public static class PostsViewHolder extends RecyclerView.ViewHolder {

        public TextView qoute, favourit_count, seen_count;
        public ImageView thumbnail;
        public LikeButton like_button;
        View itemView;

        public PostsViewHolder(final View itemView) {
            super(itemView);
            this.itemView = itemView;

            qoute = itemView.findViewById(R.id.qoutes);
            thumbnail = itemView.findViewById(R.id.thumbnail);
            favourit_count = itemView.findViewById(R.id.favourit);
            seen_count = itemView.findViewById(R.id.seen_count);

            like_button = (LikeButton) itemView.findViewById(R.id.like_button);
        }
    }
}`

**Comment by mohamedebrahim96** [comment]
all i want when i click like make toast ...as simple

**Comment by mohamedebrahim96** [comment]
when i make some likes and scroll down ..after 10 items i found some liked item
![435343543](https://user-images.githubusercontent.com/16405013/28605247-cf558390-71d0-11e7-9de8-6a4cac797716.JPG)

**Comment by mohamedebrahim96** [comment]
how can i disable automatic like button

**Comment by jd-alexander** [comment]
At a glance you can simply just set the state of the button for each row just to be sure it has the appropriate state when the view is rendered.

**Comment by jd-alexander** [comment]
What I mean is, have some form of condition that is actually setting if the button should be liked or not in the BindViewHolder function like so. 

`if(liked)
{
       likeButton.setLiked(true);
}
else
{
     likeButton.setLiked(false);
}
`

**Comment by mohamedebrahim96** [comment]
thanks sir ..you save my time
