### ISSUE TITLE
Does Icon has extra inbuilt margin at left and right?

### ISSUE THREAD

**Issue by ashishkudale** [jd-alexander/LikeButton#58]
Hi, It's really nice animation. I have used this icon beside ImageView. It shows very long gap between like icon and my ImageView. I didn't use any margin. 
Here is my xml

```
<com.like.LikeButton
                android:id="@+id/star_button"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content" 
                app:icon_type="heart" />
<ImageView
                android:id="@+id/ivDownload"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:clickable="true"
                sothree:srcCompat="@drawable/download_effect" />
```
Please see image below. 

![screenshot_2017-08-04-15-00-22](https://user-images.githubusercontent.com/10657554/28963755-e3b12642-7927-11e7-8ecd-4734bf14f161.png)

**Comment by haldertaer** [comment]
I want a fix to this simple problem right now!

**Comment by jd-alexander** [comment]
It's showing that gap because the icon needs space for the explosion animation to take place so the layout itself has margin.

**Comment by haldertaer** [comment]
Why can't the explosion animation take place over other UI elements?

**Comment by jd-alexander** [comment]
I am gonna see if I can work on improving that.

**Comment by jstr14** [comment]
Any new about this topic? I'm interested to remove the margins

**Comment by jd-alexander** [comment]
For now that support won't be apart of the library. If you are interested in adding that, contributions are welcome.
