### ISSUE TITLE
Cant disable button

### ISSUE THREAD

**Issue by jkwiecien** [jd-alexander/LikeButton#6]
None of the following methods setEnabled() setClickable or setFocusableInTouchMode() set to false seem to disable the button. Can we currently stop it from being enabled?

Only workaround I found is by setting ```OnTouchListener```:

```upvoteButton.setOnTouchListener(new View.OnTouchListener() {
                    @Override
                    public boolean onTouch(View v, MotionEvent event) {
                        return true;
                    }
                });```

**Comment by jd-alexander** [comment]
Okay I will add a setEnabled function and make a new release.

**Comment by jd-alexander** [comment]
That functionality has been added. See docs : https://github.com/jd-alexander/LikeButton#button-state
