### ISSUE TITLE
Conflict in app Manifest xml due to unnecessary attributes allowBackup and supportsRtl in the library manifest file

### ISSUE THREAD

**Issue by tushar-acharya** [jd-alexander/LikeButton#61]

**Comment by tushar-acharya** [comment]
@jd-alexander Please let me know if you have any feedback, I'll modify the PR. If not, request you to please release a new version with this and #60 Thanks!

**Comment by jd-alexander** [comment]
I will make a new release in by tomorrow. Thanks for your help.
