### ISSUE TITLE
Like button doesn't show up

### ISSUE THREAD

**Issue by YuganshT7** [jd-alexander/LikeButton#66]
I have created my Like button in a Coordinator Layout 
But the button is not visible
What should i do?
`    <com.like.LikeButton
        android:id="@+id/fav_toggle"
        android:layout_width="28dp"
        android:layout_height="28dp"
        android:layout_gravity="top|right"
        android:layout_margin="16dp"
        app:icon_size="32dp"
        app:icon_type="heart"
        app:is_enabled="true"
        app:like_drawable="@drawable/fav_white_full"
        app:liked="true"
        android:background="@color/colorAccent"
        app:unlike_drawable="@drawable/fav_white_border" />`

**Comment by jd-alexander** [comment]
If the button isn't showing up utilizing your layout editor and see where inside the view the button is located.
