### ISSUE TITLE
Icon size remains same

### ISSUE THREAD

**Issue by YuganshT79** [jd-alexander/LikeButton#68]
No matter what i do the icoz size remains same
What to do ?

    <RelativeLayout` xmlns:android="http://schemas.android.com/apk/res/android"
         xmlns:ads="http://schemas.android.com/apk/res-auto"
         xmlns:app="http://schemas.android.com/tools"
         android:layout_width="match_parent"
         android:layout_height="match_parent"
         android:background="@color/colorBackground"
         android:clickable="false"
         android:orientation="vertical">    
        
        <com.like.LikeButton
        android:id="@+id/fav"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:icon_size="145dp"
        app:icon_type="heart" />
       </RelativeLayout>

**Comment by jd-alexander** [comment]
I just tried to reproduce this and I didnt encounter this issue. If you want me to reopen you will have to create a repo that reproduces that, until then this is closed.
