### ISSUE TITLE
Error:(53, 13) Failed to resolve: com.github.jd-alexander:LikeButton:0.2.2

### ISSUE THREAD

**Issue by vinc4** [jd-alexander/LikeButton#70]
how do i fix this and whats the latest realse

**Comment by codxrs** [comment]
latest release is 0.2.3
so it must be :
compile 'com.github.jd-alexander:LikeButton:0.2.3'

And you need to add this in root gradle file :

allprojects {
	repositories {
		...
		maven { url "https://jitpack.io" }
	}
}

**Comment by rasik1991** [comment]
@codxrs it works for me thx...

**Comment by dfloresgonz** [comment]
does not work here

**Comment by jd-alexander** [comment]
@dfloresgonz are you sure? Tested the latest version and it's fine.

**Comment by dfloresgonz** [comment]
I had to delete my .gradle folder to make it work. I think it got corrupted or something, thanks.
