### ISSUE TITLE
Sparks are not antialiased

### ISSUE THREAD

**Issue by connyduck** [jd-alexander/LikeButton#72]
I think it looks really ugly especially on low resolution devices.
This zoomed-in mid-animation screenshot ilustrates the problem.
![screenshot_20171110-100950](https://user-images.githubusercontent.com/10157047/32651022-39719470-c600-11e7-9b3d-a14f1c8f18bd.png)

I guess to fix that `setAntiAlias(true)` has to be set on all Paints. I can send you a pull request if you want.

**Comment by jd-alexander** [comment]
Yes, send me a pull request.
