### ISSUE TITLE
Like button animation doesn't work

### ISSUE THREAD

**Issue by aya-salama1989** [jd-alexander/LikeButton#75]
Hi joel
We are using like Button in our app in RecyclerViews and otherViews like following;
`     <com.like.LikeButton
                    android:id="@+id/btn_fav"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="top|right"
                    app:anim_scale_factor="2.5"
                    app:circle_end_color="@color/heartOn"
                    app:circle_start_color="@android:color/holo_red_dark"
                    app:dots_primary_color="@color/heartOn"
                    app:dots_secondary_color="@android:color/holo_red_dark"
                    app:icon_size="25dp"
                    app:like_drawable="@drawable/heart_on"
                    app:unlike_drawable="@drawable/heart_off" />`

using latest version `compile 'com.github.jd-alexander:LikeButton:0.2.3'`

It works totally fine but,
the issue is: animation doesn't work at all cases, we tested it through the following OS; Lollipop, Marshmallow, Nougat and Oreo

Is there's something we're doing wrong in development?
Is there's another way to set and activate animations on the button?

Thanks (f)

**Comment by Anandsoni14** [comment]
Same thing is happening to me.

**Comment by jd-alexander** [comment]
I am gonna check this out. You ran the sample and this error is taking place?

**Comment by aya-salama1989** [comment]
@jd-alexander  just tested the sample and it's working fine, but our code is not although we're following the same methodologies

**Comment by jd-alexander** [comment]
I think it's probably a recyclerview issue then so I am gonna try and add a recycler view example in the sample and see what happens.

**Comment by Anandsoni14** [comment]
Things are working now but not expected it should be. Like ` app:circle_end_color="@color/pink_variant"
                app:circle_start_color="@color/colorPrimary"
                app:dots_primary_color="@color/green_variant"
                app:dots_secondary_color="@color/orange_variant"`
are not working . then like_drawable is different from what I defined it .

**Comment by aya-salama1989** [comment]
@jd-alexander Actually we are using it separately in LinearLayouts and other layout variations, brushed on your sample, couldn't find changes between our work and the sample

**Comment by jd-alexander** [comment]
I am gonna work on a manual way to trigger the animation.

**Comment by LinkOut** [comment]
Same problem here

**Comment by pamgoudarzi** [comment]
Beware that if you set any OnClickListeners on the like button it will disable animations. At least, that's what I experienced.

**Comment by jd-alexander** [comment]
I haven't been able to reproduce these errors. Please upload a sample repo so I can see the error and address it, until then I am closing this issue.
