### ISSUE TITLE
Caused by: android.view.InflateException: Binary XML file line #0: Error inflating class com.like.LikeButton

### ISSUE THREAD

**Issue by ZeroCool00** [jd-alexander/LikeButton#78]
i just update my android studio and update gradle dependency to 27. now i m not able to inflate likebutton class.
 i m using this version.
implementation 'com.github.jd-alexander:LikeButton:0.2.3' 
is there anything i m missing for newer version.

**Comment by jd-alexander** [comment]
Im really not sure. Did you get this issue resolved?

**Comment by SHP-Hari** [comment]
still this occurs
