### ISSUE TITLE
Animation bugs when using LikeButton in RecyclerView

### ISSUE THREAD

**Issue by RealityTest** [jd-alexander/LikeButton#82]
I use the LikeButton for each element in my RecyclerView. However, it's very glitchy. Most of tihe time the animation plays for the wrong item. Sometimes it doesn't play at all. Often I have to like, unlike and like it again for the animation to play. Any way to fix this behaviour?

**Comment by jd-alexander** [comment]
Could you give me some more details so that I can reproduce?

**Comment by RealityTest** [comment]
Sure, I'm having the bug in my repository: https://github.com/RealityTest/SuggestaMovie 

`  @Override
  public void onBindViewHolder(final RecyclerViewMovieAdapter.ViewHolder holder, int position) {
    final Movie movie = movies.get(position);
    if (movie.getPosterPath() != null) {
      String posterUrl = imgUrlBasePath + movie.getPosterPath();
      Log.d(TAG, "Poster URL " + movie.getTitle() + ": " + posterUrl);
      Picasso.with(context).load(posterUrl).placeholder(R.drawable.placeholder_thumbnail).error(R.drawable.placeholder_thumbnail).into(holder.imgThumbnail);
      holder.textTitle.setText(movie.getTitle());
      holder.textRating.setText(String.format(context.getString(R.string.rating_format), movie.getVoteAverage()));
      holder.textRelease.setText(String.format(context.getString(R.string.release_format), movie.getReleaseDate()));

      if (!showBtnFavorite) {
        holder.btnFavorite.setVisibility(View.GONE);
      }
      if (watchlist.contains(movie)) {
        holder.btnFavorite.setLiked(true);
      } else {
        holder.btnFavorite.setLiked(false);
      }
      holder.btnFavorite.setOnLikeListener(new OnLikeListener() {
        @Override
        public void liked(LikeButton likeButton) {
          watchlist.add(movie);
          notifyDataSetChanged();
          serializer.writeWatchlist(watchlist);
        }

        @Override
        public void unLiked(LikeButton likeButton) {
          watchlist.remove(movie);
          notifyDataSetChanged();
          serializer.writeWatchlist(watchlist);
        }
      });
    }
  }`

This is the code I use in the RecyclerView adapter

and this is the Layout:

`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="210dp"
              xmlns:app="http://schemas.android.com/apk/res-auto"
              android:paddingBottom="16dp"
              android:paddingTop="16dp"
              android:orientation="vertical"
              android:adjustViewBounds="true">

  <RelativeLayout
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:orientation="horizontal">

    <ImageView
      android:id="@+id/img_thumbnail_movie"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:adjustViewBounds="true"
      android:contentDescription="@string/content_descr_thumbnail"
      android:maxHeight="210dp"
      android:src="@drawable/placeholder_thumbnail"/>

    <LinearLayout
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:orientation="vertical"
      android:layout_toRightOf="@+id/img_thumbnail_movie"
      android:layout_toEndOf="@+id/img_thumbnail_movie"
      android:paddingLeft="16dp"
      android:paddingStart="16dp">

      <TextView
        android:id="@+id/text_movie_title"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:textSize="16sp"
        android:textStyle="bold"
        android:text="Movie Title"/>

      <TextView
        android:id="@+id/text_movie_rating"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:drawableStart="@drawable/ic_star_black_24dp"
        android:drawableLeft="@drawable/ic_star_black_24dp"
        android:ellipsize="end"
        android:paddingTop="16dp"
        android:text="Rating: 7.4/10"/>

      <TextView
        android:id="@+id/text_movie_release"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:drawableStart="@drawable/ic_date_range_black_24dp"
        android:drawableLeft="@drawable/ic_date_range_black_24dp"
        android:ellipsize="end"
        android:paddingTop="16dp"
        android:text="Release: 2018-01-02"/>

    </LinearLayout>

    <RelativeLayout
      android:layout_width="wrap_content"
      android:layout_height="wrap_content">

      <com.like.LikeButton
        android:id="@+id/btn_favorite"
        app:icon_type="star"
        app:icon_size="24dp"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        app:unlike_drawable="@drawable/ic_star_border_yellow_24dp"
        app:like_drawable="@drawable/ic_star_yellow_24dp"
        app:anim_scale_factor="2"
        android:layout_alignParentBottom="true"
        android:layout_alignParentEnd="true"
        app:liked="false"/>

    </RelativeLayout>

  </RelativeLayout>

</LinearLayout>`

**Comment by connyduck** [comment]
Its because you are invalidating the whole recyclerview with `notifyDataSetChanged()`. Try calling `notifyItemChanged(int position) ` instead.

**Comment by RealityTest** [comment]
Thank you @connyduck that fixed it.
