### ISSUE TITLE
Start heart color

### ISSUE THREAD

**Issue by Mhm0ud** [jd-alexander/LikeButton#84]
Can I change the first heart color? (it's now gray)

**Comment by jd-alexander** [comment]
Yes you can. All you have to do is get an instance of the drawable and modify the colour. If you aren't clear on this let me know and I will post some code here.

**Comment by SangKarthi94** [comment]
Can you please post the code i cant able to change the icon or color of icon

**Comment by joaogarrido98** [comment]
can you post the code?
