### ISSUE TITLE
want to call liked function after condition checked rather than directly call on setOnLikeListener

### ISSUE THREAD

**Issue by ksh2lmh** [jd-alexander/LikeButton#87]
I want to start liked animation after i checked condition rather than directly call liked animation function on setonclicklistener.
After click on liked button some condition checked .if that condion true then only liked animation or function call

**Comment by SachinSoma** [comment]
Its Simple inside liked function check your condition and set liked true like this..
```
 @Override
    public void liked(LikeButton likeButton) {
if(condition)
{
        likeButton.setLiked(true);
}
  }

    @Override
    public void unLiked(LikeButton likeButton) {
        likeButton.setLiked(false);
 }
```
