### ISSUE TITLE
EventListener on Kotlin

### ISSUE THREAD

**Issue by WeeHong** [jd-alexander/LikeButton#88]
Hello.

May I know how to implement the `setOnClickListener` in Kotlin?

I tried the following method, but it is not working.

```
likeButton.setOnLikeListener(object: OnLikeListener() {
    @Override
    fun void liked(LikeButton likeButton) {

    }

    @Override
    fun void unLiked(LikeButton likeButton) {

    }
})
```

**Comment by jd-alexander** [comment]
@WeeHong give me a moment to check this out and get back to you.

**Comment by WeeHong** [comment]
@jd-alexander Thank you very much.

**Comment by Suraj12p** [comment]
I tired this within a recylerView, no error in code but crashes on launch of activity

                likeButton.setOnLikeListener(object: OnLikeListener {
                    override fun liked(p0: LikeButton?) {
                        Toast.makeText(this@YourActivity, "Liked", Toast.LENGTH_SHORT).show()
                    }

                    override fun unLiked(p0: LikeButton?) {
                        Toast.makeText(this@YourActivity, "Unliked", Toast.LENGTH_SHORT).show()
                    }
                })

however get this error

    java.lang.NullPointerException: Attempt to invoke virtual method 'void com.like.LikeButton.setOnLikeListener(com.like.OnLikeListener)' on a null object reference

XML:

            <com.like.LikeButton
                android:id="@+id/likeButton"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentEnd="true"
                android:layout_below="@+id/imgView"
                android:layout_marginEnd="60dp"
                app:icon_size="25dp"
                app:icon_type="heart" />

Hope this helps solve this, if i find a fix i'll update

**Comment by WeeHong** [comment]
@Suraj12p 

Mean this is still not compatible with Kotlin yet?

**Comment by Suraj12p** [comment]
@WeeHong I got it to work use it like this

                mLiveVH.itemView.likeButton.setOnLikeListener(object: OnLikeListener {
                    override fun liked(likeButton: LikeButton?) {
                        Toast.makeText(this@YourActivity, "Liked", Toast.LENGTH_SHORT).show()
                    }

                    override fun unLiked(likeButton: LikeButton?) {
                        Toast.makeText(this@YourActivity, "Unliked", Toast.LENGTH_SHORT).show()

                    }
                })


This fixes the issues I had using it in a recyclerView, it does work with Kotlin

**Comment by WeeHong** [comment]
Still cannot do it with my case. Nevermind.

I will go for ImageButton.
