### ISSUE TITLE
binary exception on oncreate

### ISSUE THREAD

**Issue by Sree1894** [jd-alexander/LikeButton#89]
While trying to load all the three like heart and star in a page causing binary exception .Memory is full while loading the page .Do you have any alternate idea to resolve this issue

**Comment by jd-alexander** [comment]
Can you show me the stacktrace?

**Comment by jd-alexander** [comment]
Let me see the XML you are using. Something is going wrong with the way how you are using it.

**Comment by Sree1894** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@drawable/bckgrndone"
    android:theme="@style/playscreentheme"
    android:orientation="vertical"
    android:weightSum="3"
    android:id="@+id/mainlinearlayout"
    android:visibility="visible">



        

        <LinearLayout
            android:id="@+id/playcontrollayout"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1.6"
            android:orientation="vertical">

            
                
                
                
                
                
                
                

            
            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:gravity="center"
                android:layout_gravity="center"
                android:layout_marginTop="20dp">
            <ImageView
                android:id="@+id/backbutton"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:scaleType="fitXY"
                android:src="@drawable/backarrow"
                android:layout_marginEnd="20dp"/>

                <Button
                    android:id="@+id/buttonplaypause"
                    android:layout_width="65dp"
                    android:layout_height="65dp"
                    android:background="@drawable/playbutton"
                    />



            <ImageView
                android:id="@+id/nextbutton"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:scaleType="fitXY"
                android:src="@drawable/nextarrow"
                android:layout_marginStart="20sp"/>
                
            </LinearLayout>


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:layout_marginTop="5dp">


                <SeekBar
                    android:id="@+id/seektime"
                    android:layout_width="200dp"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:progress="50"
                    android:padding="5dp"
                    android:secondaryProgressTintMode="add"
                    android:layout_marginTop="10sp"
                    />
                <TextView
                    android:id="@+id/textvduration"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="(1:10)"
                    android:textColor="@color/colorlightred"
                    android:gravity="center"
                    android:layout_gravity="center"/>

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal"
                    android:gravity="center"
                    android:layout_gravity="center_horizontal"
                    android:layout_marginTop="0sp">


                        
                            
                            
                            
                            
                        
                            
                            
                            
                            
                            

                        <SeekBar
                            android:id="@+id/volumeseekbar"
                            android:layout_width="300dp"
                            android:layout_height="wrap_content"
                            android:progress="50"
                            />

                    </LinearLayout>



            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="horizontal"
                android:layout_gravity="bottom"
                android:gravity="bottom"
                android:weightSum="5"
                >
                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:layout_gravity="bottom"
                    android:gravity="center"
                    android:orientation="horizontal">


                    <com.like.LikeButton
                        app:icon_type="Like"
                        android:layout_width="40dp"
                        android:layout_height="40dp"
                        app:icon_size="22sp" />

                    <TextView
                        android:id="@+id/liketextview"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textSize="14sp"
                        android:text="12"
                        android:gravity="center"
                        android:textColor="@color/colorlightred"
                        />
                </LinearLayout>


                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:gravity="center"
                    android:orientation="horizontal">
                   
                       
                       
                       
                       
                    <TextView
                        android:id="@+id/hearttextview"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:textSize="14sp"
                        android:text="12"
                        android:gravity="center"
                        android:textColor="@color/colorlightred"
                        />
                </LinearLayout>
                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:orientation="horizontal">

                    
                        
                        
                        
                        
                    <TextView
                        android:id="@+id/sadtextview"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:textSize="14sp"
                        android:text="12"
                        android:gravity="center"
                        android:textColor="@color/colorlightred"
                        />
                </LinearLayout>
                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1.2"
                    android:orientation="horizontal">


                        
                            
                            
                            
                            
                            
                            
                            
                            

                        <TextView
                            android:id="@+id/commentstextview"
                            android:layout_width="wrap_content"
                            android:layout_height="match_parent"
                            android:textSize="14sp"
                            android:text="12"
                            android:gravity="center"
                            android:textColor="@color/colorlightred"
                            android:layout_marginEnd="5dp"
                            />

                </LinearLayout>

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="0.8"
                    android:gravity="center"
                    android:orientation="horizontal">

                    <ImageView
                        android:id="@+id/sharebutton"
                        android:layout_width="40sp"
                        android:layout_height="40sp"
                        android:src="@drawable/share_button"
                        android:scaleType="fitXY"
                        android:padding="4dp"/>
                </LinearLayout>
            </LinearLayout>

        </LinearLayout>
        
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="0.4"
            android:orientation="vertical"
            android:gravity="center"
            android:background="#eeeeee">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="17/01/2018"
                android:textColor="@color/colorlightred"
                android:gravity="center"
                android:padding="5dp"
                android:textSize="18sp"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="CEO TOWNHALL MEET"
                android:textColor="@color/colorlightred"
                android:gravity="center"
                android:padding="5dp"
                android:textSize="18sp"/>
        </LinearLayout>



</LinearLayout>

**Comment by Sree1894** [comment]
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:background="@drawable/bckgrndone"
    android:theme="@style/playscreentheme"
    android:orientation="vertical"
    android:weightSum="3"
    android:id="@+id/mainlinearlayout"
    android:visibility="visible">



        

        <LinearLayout
            android:id="@+id/playcontrollayout"
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1.6"
            android:orientation="vertical">

            
                
                
                
                
                
                
                

            
            <LinearLayout
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:orientation="horizontal"
                android:gravity="center"
                android:layout_gravity="center"
                android:layout_marginTop="20dp">
            <ImageView
                android:id="@+id/backbutton"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:scaleType="fitXY"
                android:src="@drawable/backarrow"
                android:layout_marginEnd="20dp"/>


                <Button
                    android:id="@+id/buttonplaypause"
                    android:layout_width="65dp"
                    android:layout_height="65dp"
                    android:background="@drawable/playbutton"
                    />



            <ImageView
                android:id="@+id/nextbutton"
                android:layout_width="40dp"
                android:layout_height="40dp"
                android:scaleType="fitXY"
                android:src="@drawable/nextarrow"
                android:layout_marginStart="20sp"/>
                
            </LinearLayout>


            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:orientation="vertical"
                android:layout_marginTop="5dp">


                <SeekBar
                    android:id="@+id/seektime"
                    android:layout_width="200dp"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:progress="50"
                    android:padding="5dp"
                    android:secondaryProgressTintMode="add"
                    android:layout_marginTop="10sp"
                    />
                <TextView
                    android:id="@+id/textvduration"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:text="(1:10)"
                    android:textColor="@color/colorlightred"
                    android:gravity="center"
                    android:layout_gravity="center"/>

                <LinearLayout
                    android:layout_width="match_parent"
                    android:layout_height="wrap_content"
                    android:orientation="horizontal"
                    android:gravity="center"
                    android:layout_gravity="center_horizontal"
                    android:layout_marginTop="0sp">


                        
                            
                            
                            
                            
                        
                            
                            
                            
                            
                            


                        <SeekBar
                            android:id="@+id/volumeseekbar"
                            android:layout_width="300dp"
                            android:layout_height="wrap_content"
                            android:progress="50"
                            />

                    </LinearLayout>



            </LinearLayout>

            <LinearLayout
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                android:orientation="horizontal"
                android:layout_gravity="bottom"
                android:gravity="bottom"
                android:weightSum="5"
                >

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:layout_gravity="bottom"
                    android:gravity="center"
                    android:orientation="horizontal">


                    <com.like.LikeButton
                        app:icon_type="Like"
                        android:layout_width="40dp"
                        android:layout_height="40dp"
                        app:icon_size="22sp" />

                    <TextView
                        android:id="@+id/liketextview"
                        android:layout_width="wrap_content"
                        android:layout_height="wrap_content"
                        android:textSize="14sp"
                        android:text="12"
                        android:gravity="center"
                        android:textColor="@color/colorlightred"
                        />
                </LinearLayout>


                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:gravity="center"
                    android:orientation="horizontal">
                   
                       
                       
                       
                       
                    <TextView
                        android:id="@+id/hearttextview"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:textSize="14sp"
                        android:text="12"
                        android:gravity="center"
                        android:textColor="@color/colorlightred"
                        />
                </LinearLayout>

                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1"
                    android:orientation="horizontal">

                    
                        
                        
                        
                        
                    <TextView
                        android:id="@+id/sadtextview"
                        android:layout_width="match_parent"
                        android:layout_height="match_parent"
                        android:textSize="14sp"
                        android:text="12"
                        android:gravity="center"
                        android:textColor="@color/colorlightred"
                        />
                </LinearLayout>


                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="1.2"
                    android:orientation="horizontal">


                        
                            
                            
                            
                            
                            
                            
                            
                            



                        <TextView
                            android:id="@+id/commentstextview"
                            android:layout_width="wrap_content"
                            android:layout_height="match_parent"
                            android:textSize="14sp"
                            android:text="12"
                            android:gravity="center"
                            android:textColor="@color/colorlightred"
                            android:layout_marginEnd="5dp"
                            />


                </LinearLayout>


                <LinearLayout
                    android:layout_width="0dp"
                    android:layout_height="match_parent"
                    android:layout_weight="0.8"
                    android:gravity="center"
                    android:orientation="horizontal">

                    <ImageView
                        android:id="@+id/sharebutton"
                        android:layout_width="40sp"
                        android:layout_height="40sp"
                        android:src="@drawable/share_button"
                        android:scaleType="fitXY"
                        android:padding="4dp"/>
                </LinearLayout>




            </LinearLayout>

        </LinearLayout>





        

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="0.4"
            android:orientation="vertical"
            android:gravity="center"
            android:background="#eeeeee">

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="17/01/2018"
                android:textColor="@color/colorlightred"
                android:gravity="center"
                android:padding="5dp"
                android:textSize="18sp"/>

            <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="CEO TOWNHALL MEET"
                android:textColor="@color/colorlightred"
                android:gravity="center"
                android:padding="5dp"
                android:textSize="18sp"/>

        </LinearLayout>





        

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="0dp"
            android:layout_weight="1"
            android:orientation="vertical">

                <TextView
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textColor="@color/colorlightred"
                    android:textSize="18sp"
                    android:text="Feed Archives"
                    android:textStyle="bold"
                    android:padding="5dp"/>


            <it.sephiroth.android.library.widget.HListView
                android:id="@+id/libhrlistview"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
               >

            </it.sephiroth.android.library.widget.HListView>

        </LinearLayout>




</LinearLayout>
