### ISSUE TITLE
How to set the button state

### ISSUE THREAD

**Issue by Abhishekwayindia** [jd-alexander/LikeButton#91]
likebutton.setLiked(true); doesn't working whenever I reload the activity again. whenever I enter into the activity the heart button is in the previous state even I clicked it before . The same thing is happening with likeButton.setEnabled(false); .

**Comment by Nishit79** [comment]
Getting same issue.
Please refer "https://github.com/varunest/SparkButton" for the same.
Both have same functionality but this one is more feasible and contains no limitation.
