### ISSUE TITLE
Failed to reslove: com.github.jd-alexander:LikeButton:0.2.3 

### ISSUE THREAD

**Issue by AliYar-Khan** [jd-alexander/LikeButton#94]
I have tried to add dependencies but it fails with the error mention in the title of the issue

**Comment by muayyadayesh** [comment]
You should edit your project gradle file by adding : 

`        maven { url 'https://jitpack.io' }
`

after allprojects.

**Comment by codingcity4747** [comment]
when adding maven{url 'https://jitpack.io'}
every thing is ok
thanks @muayyadayesh
