### ISSUE TITLE
Failed to resolve: com.github <a href=""</a> com.github.jd-alexander:LikeButton:0.2.3'

### ISSUE THREAD

**Issue by ameybawiskar** [jd-alexander/LikeButton#99]
I Currently using `com.github.jd-alexander:LikeButton:0.2.3'` library till today everything was fine .
but somehow what happened dont know i getting error **### Failed to resolve: com.github <a href=""</a> com.github.jd-alexander:LikeButton:0.2.3'**

help Appreciate

**Comment by codingcity4747** [comment]
add   maven { url 'https://jitpack.io' } in allrepository in build.gradle project after that add the dependency
then sync , that's it 💃 @ameybawiskar

**Comment by IronDigitalMedia** [comment]
Thanks @codingcity4747  that solution worked for me.
